// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hello.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PubsubPayload_Type int32

const (
	PubsubPayload_TYPE_UNSPECIFIED PubsubPayload_Type = 0
	PubsubPayload_TEXT             PubsubPayload_Type = 1
	PubsubPayload_IMAGE            PubsubPayload_Type = 2
	PubsubPayload_AUDIO            PubsubPayload_Type = 3
	PubsubPayload_VIDEO            PubsubPayload_Type = 4
)

var PubsubPayload_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "TEXT",
	2: "IMAGE",
	3: "AUDIO",
	4: "VIDEO",
}

var PubsubPayload_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"TEXT":             1,
	"IMAGE":            2,
	"AUDIO":            3,
	"VIDEO":            4,
}

func (x PubsubPayload_Type) String() string {
	return proto.EnumName(PubsubPayload_Type_name, int32(x))
}

func (PubsubPayload_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{2, 0}
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PubsubPayload struct {
	Type PubsubPayload_Type `protobuf:"varint,1,opt,name=type,proto3,enum=reimagined_couscous.PubsubPayload_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Avatar:
	//	*PubsubPayload_ImageUrl
	//	*PubsubPayload_ImageData
	Avatar               isPubsubPayload_Avatar           `protobuf_oneof:"avatar"`
	Nested               *PubsubPayload_Nested            `protobuf:"bytes,4,opt,name=nested,proto3" json:"nested,omitempty"`
	Nums                 []int32                          `protobuf:"varint,5,rep,packed,name=nums,proto3" json:"nums,omitempty"`
	NestedMap            map[string]*PubsubPayload_Nested `protobuf:"bytes,6,rep,name=nested_map,json=nestedMap,proto3" json:"nested_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Completed            bool                             `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
	LastUpdated          *timestamp.Timestamp             `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *PubsubPayload) Reset()         { *m = PubsubPayload{} }
func (m *PubsubPayload) String() string { return proto.CompactTextString(m) }
func (*PubsubPayload) ProtoMessage()    {}
func (*PubsubPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{2}
}

func (m *PubsubPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubsubPayload.Unmarshal(m, b)
}
func (m *PubsubPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubsubPayload.Marshal(b, m, deterministic)
}
func (m *PubsubPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubsubPayload.Merge(m, src)
}
func (m *PubsubPayload) XXX_Size() int {
	return xxx_messageInfo_PubsubPayload.Size(m)
}
func (m *PubsubPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PubsubPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PubsubPayload proto.InternalMessageInfo

func (m *PubsubPayload) GetType() PubsubPayload_Type {
	if m != nil {
		return m.Type
	}
	return PubsubPayload_TYPE_UNSPECIFIED
}

type isPubsubPayload_Avatar interface {
	isPubsubPayload_Avatar()
}

type PubsubPayload_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type PubsubPayload_ImageData struct {
	ImageData []byte `protobuf:"bytes,3,opt,name=image_data,json=imageData,proto3,oneof"`
}

func (*PubsubPayload_ImageUrl) isPubsubPayload_Avatar() {}

func (*PubsubPayload_ImageData) isPubsubPayload_Avatar() {}

func (m *PubsubPayload) GetAvatar() isPubsubPayload_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *PubsubPayload) GetImageUrl() string {
	if x, ok := m.GetAvatar().(*PubsubPayload_ImageUrl); ok {
		return x.ImageUrl
	}
	return ""
}

func (m *PubsubPayload) GetImageData() []byte {
	if x, ok := m.GetAvatar().(*PubsubPayload_ImageData); ok {
		return x.ImageData
	}
	return nil
}

func (m *PubsubPayload) GetNested() *PubsubPayload_Nested {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *PubsubPayload) GetNums() []int32 {
	if m != nil {
		return m.Nums
	}
	return nil
}

func (m *PubsubPayload) GetNestedMap() map[string]*PubsubPayload_Nested {
	if m != nil {
		return m.NestedMap
	}
	return nil
}

func (m *PubsubPayload) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *PubsubPayload) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PubsubPayload) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PubsubPayload_ImageUrl)(nil),
		(*PubsubPayload_ImageData)(nil),
	}
}

type PubsubPayload_Nested struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubsubPayload_Nested) Reset()         { *m = PubsubPayload_Nested{} }
func (m *PubsubPayload_Nested) String() string { return proto.CompactTextString(m) }
func (*PubsubPayload_Nested) ProtoMessage()    {}
func (*PubsubPayload_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{2, 0}
}

func (m *PubsubPayload_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubsubPayload_Nested.Unmarshal(m, b)
}
func (m *PubsubPayload_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubsubPayload_Nested.Marshal(b, m, deterministic)
}
func (m *PubsubPayload_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubsubPayload_Nested.Merge(m, src)
}
func (m *PubsubPayload_Nested) XXX_Size() int {
	return xxx_messageInfo_PubsubPayload_Nested.Size(m)
}
func (m *PubsubPayload_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_PubsubPayload_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_PubsubPayload_Nested proto.InternalMessageInfo

func (m *PubsubPayload_Nested) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PubsubPayload_Nested) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("reimagined_couscous.PubsubPayload_Type", PubsubPayload_Type_name, PubsubPayload_Type_value)
	proto.RegisterType((*HelloRequest)(nil), "reimagined_couscous.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "reimagined_couscous.HelloResponse")
	proto.RegisterType((*PubsubPayload)(nil), "reimagined_couscous.PubsubPayload")
	proto.RegisterMapType((map[string]*PubsubPayload_Nested)(nil), "reimagined_couscous.PubsubPayload.NestedMapEntry")
	proto.RegisterType((*PubsubPayload_Nested)(nil), "reimagined_couscous.PubsubPayload.Nested")
}

func init() {
	proto.RegisterFile("proto/hello.proto", fileDescriptor_f7116fbf19896b02)
}

var fileDescriptor_f7116fbf19896b02 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x9b, 0x36, 0xed, 0xd2, 0xb7, 0xae, 0x0a, 0x86, 0x43, 0x54, 0x81, 0x16, 0x72, 0x21,
	0x93, 0x20, 0xd1, 0xca, 0x05, 0x81, 0x10, 0xea, 0x68, 0x68, 0x7b, 0x58, 0x57, 0xa5, 0x2d, 0x02,
	0x0e, 0x54, 0x6e, 0x63, 0xb2, 0x40, 0x12, 0x87, 0xd8, 0x99, 0x94, 0xff, 0x9d, 0x03, 0xb2, 0xd3,
	0xa8, 0x0c, 0x4d, 0x68, 0x1c, 0xa2, 0x7c, 0xb6, 0xbf, 0x9f, 0xfd, 0xfc, 0xde, 0x33, 0x3c, 0xc8,
	0x72, 0xca, 0xa9, 0x7b, 0x4d, 0xe2, 0x98, 0x3a, 0x52, 0xa3, 0x87, 0x39, 0x89, 0x12, 0x1c, 0x46,
	0x29, 0x09, 0x36, 0x3b, 0x5a, 0x30, 0xf1, 0x0d, 0x4e, 0x43, 0x4a, 0xc3, 0x98, 0xb8, 0xd2, 0xb2,
	0x2d, 0xbe, 0xb9, 0x3c, 0x4a, 0x08, 0xe3, 0x38, 0xc9, 0x2a, 0xca, 0xb2, 0xa0, 0x37, 0x15, 0x9b,
	0xf8, 0xe4, 0x67, 0x41, 0x18, 0x47, 0x08, 0xd4, 0x14, 0x27, 0xc4, 0x50, 0x4c, 0xc5, 0xee, 0xfa,
	0x52, 0x5b, 0x67, 0x70, 0xb2, 0xf7, 0xb0, 0x8c, 0xa6, 0x8c, 0x20, 0x03, 0x8e, 0x12, 0xc2, 0x18,
	0x0e, 0x6b, 0x5f, 0x3d, 0xb4, 0x7e, 0xa9, 0x70, 0xb2, 0x28, 0xb6, 0xac, 0xd8, 0x2e, 0x70, 0x19,
	0x53, 0x1c, 0xa0, 0x37, 0xa0, 0xf2, 0x32, 0xab, 0x8c, 0xfd, 0xe1, 0x33, 0xe7, 0x8e, 0x28, 0x9d,
	0x5b, 0x84, 0xb3, 0x2a, 0x33, 0xe2, 0x4b, 0x08, 0x3d, 0x81, 0xae, 0x70, 0x93, 0x4d, 0x91, 0xc7,
	0x46, 0x53, 0x1c, 0x35, 0x6d, 0xf8, 0x9a, 0x9c, 0x5a, 0xe7, 0x31, 0x3a, 0x05, 0xa8, 0x96, 0x03,
	0xcc, 0xb1, 0xd1, 0x32, 0x15, 0xbb, 0x37, 0x6d, 0xf8, 0x15, 0x32, 0xc6, 0x1c, 0xa3, 0x11, 0x74,
	0x52, 0xc2, 0x38, 0x09, 0x0c, 0xd5, 0x54, 0xec, 0xe3, 0xe1, 0xd9, 0x3d, 0x8e, 0x9f, 0x4b, 0xc0,
	0xdf, 0x83, 0x32, 0x21, 0x45, 0xc2, 0x8c, 0xb6, 0xd9, 0xb2, 0xdb, 0xbe, 0xd4, 0x68, 0x01, 0x50,
	0xad, 0x6e, 0x12, 0x9c, 0x19, 0x1d, 0xb3, 0x65, 0x1f, 0x0f, 0xcf, 0xef, 0xbd, 0xf5, 0x25, 0xce,
	0xbc, 0x94, 0xe7, 0xa5, 0xdf, 0x4d, 0xeb, 0x31, 0x7a, 0x0c, 0xdd, 0x1d, 0x4d, 0xb2, 0x98, 0x88,
	0x58, 0x8f, 0x4c, 0xc5, 0xd6, 0xfc, 0xc3, 0x04, 0x7a, 0x0b, 0xbd, 0x18, 0x33, 0xbe, 0x29, 0xb2,
	0x00, 0x0b, 0x83, 0x26, 0x2f, 0x33, 0x70, 0xaa, 0xe2, 0x3a, 0x75, 0x71, 0x9d, 0x55, 0x5d, 0x5c,
	0xff, 0x58, 0xf8, 0xd7, 0x95, 0x7d, 0xf0, 0x1c, 0x3a, 0xf3, 0xc3, 0x65, 0xfe, 0xaa, 0x2e, 0xea,
	0x43, 0x33, 0x0a, 0x64, 0x72, 0xdb, 0x7e, 0x33, 0x0a, 0x06, 0x21, 0xf4, 0x6f, 0xc7, 0x89, 0x74,
	0x68, 0xfd, 0x20, 0xe5, 0x1e, 0x12, 0x12, 0xbd, 0x83, 0xf6, 0x0d, 0x8e, 0x0b, 0x22, 0xb1, 0xff,
	0x4a, 0x6b, 0xc5, 0xbd, 0x6e, 0xbe, 0x52, 0xac, 0x09, 0xa8, 0xa2, 0xd4, 0xe8, 0x11, 0xe8, 0xab,
	0xcf, 0x0b, 0x6f, 0xb3, 0x9e, 0x2f, 0x17, 0xde, 0xfb, 0xd9, 0x87, 0x99, 0x37, 0xd6, 0x1b, 0x48,
	0x03, 0x75, 0xe5, 0x7d, 0x5a, 0xe9, 0x0a, 0xea, 0x42, 0x7b, 0x76, 0x39, 0x9a, 0x78, 0x7a, 0x53,
	0xc8, 0xd1, 0x7a, 0x3c, 0xbb, 0xd2, 0x5b, 0x42, 0x7e, 0x9c, 0x8d, 0xbd, 0x2b, 0x5d, 0xbd, 0xd0,
	0xa0, 0x83, 0x6f, 0x30, 0xc7, 0xf9, 0xf0, 0x2b, 0x1c, 0x4d, 0x72, 0x42, 0x38, 0xc9, 0xd1, 0x12,
	0xb4, 0x25, 0x2e, 0x65, 0xdf, 0xa2, 0xa7, 0x77, 0xc6, 0xf7, 0x67, 0xdf, 0x0f, 0xac, 0x7f, 0x59,
	0xaa, 0xb6, 0xb7, 0x1a, 0x17, 0xe7, 0x5f, 0xdc, 0x30, 0xe2, 0xd7, 0xc5, 0xd6, 0xd9, 0xd1, 0xc4,
	0xfd, 0x4e, 0x49, 0xc9, 0x62, 0x1c, 0xd3, 0xc4, 0x3d, 0xc0, 0x2f, 0x6a, 0x78, 0xff, 0xe6, 0x3a,
	0xf2, 0xf7, 0xf2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x17, 0xf6, 0x6a, 0xb2, 0x03, 0x00,
	0x00,
}
